/*
 * This source file was generated by the Gradle 'init' task
 */
package kr.jinsu.service_layer;

import java.util.Scanner;

import org.apache.ibatis.session.SqlSession;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import kr.jinsu.MyBatisConnectionFactory;
import kr.jinsu.exceptions.ServiceNoResultException;
import kr.jinsu.models.Student;
import kr.jinsu.services.StudentService;
import kr.jinsu.services.impl.StudentServiceImpl;

public class App01_stud {
    public static void main(String[] args) {
        
        /** 처리 결과를 기록할 Log3J 객체 색성 */
        // 파라미터는 현재 클래스의 이름(String)
        Logger logger = LogManager.getFormatterLogger(App01_stud.class);

        Scanner scanner = new Scanner(System.in);

        System.out.print("학생이름: ");
        String name = scanner.nextLine();

        System.out.print("아이디: ");
        String userid = scanner.nextLine();

        System.out.print("주민번호: ");
        String idnum = scanner.nextLine();

        System.out.print("생년월일: ");
        String birthdate = scanner.nextLine();

        System.out.print("연락처: ");
        String tel = scanner.nextLine();

        System.out.print("학년: ");
        int grade = scanner.nextInt();

        System.out.print("키: ");
        int height = scanner.nextInt();

        System.out.print("몸무게: ");
        int weight = scanner.nextInt();

        System.out.print("학과번호: ");
        int deptno = scanner.nextInt();

        System.out.print("교수번호: ");
        int profno = scanner.nextInt();

        scanner.close();
        //입력값을 로그로 기록함
        logger.debug("입력된 데이터: " + name + ", " + userid + ", " + grade + ", " + idnum + ", " + birthdate + ", " + tel + ", " + height + ", " + weight + ", " + deptno + ", " + profno);

        /** 2) 데이터베이스 접속 */
        SqlSession sqlSession = MyBatisConnectionFactory.getSqlSession();

        Student stud = new Student();
        stud.setName(name);
        stud.setUserid(userid);
        stud.setGrade(grade);
        stud.setIdnum(idnum);
        stud.setBirthdate(birthdate);
        stud.setTel(tel);
        stud.setHeight(height);
        stud.setWeight(weight);
        stud.setDeptno(deptno);
        stud.setProfno(profno);

        /** 데이터 처리 수행 */
        //비즈니스 로직을 위한 Service 객체 생성
        // --> Mapper에 정의된 SQL을 호출하기 위해 SqlSession 객체를 주입
        StudentService StudentService = new StudentServiceImpl(sqlSession);
        //저장된 결과를 리턴받기 위한 Beans 객체
        Student result = null;

        //저장된 결과를 리턴받기 위한 Beans 객체
        try {
            result = StudentService.addItem(stud);
        } catch (ServiceNoResultException e) {
            sqlSession.rollback();
            logger.error("[저장된 데이터가 없습니다.]");
            logger.error(e.getMessage());
        } catch (Exception e) {
            sqlSession.rollback();
            logger.error("[SQL문 처리에 실패했습니다. Mapper를 확인하세요.]");
            logger.error(e.getMessage());
        } finally {
            sqlSession.commit();
        }

        /** 처리 결과 출력 */
        if( result != null ) {
            logger.debug("==========================");
            logger.debug(result.toString());
            logger.debug("==========================");
        } else {
            logger.error("저장된 데이터가 없습니다.");
        }

        sqlSession.close();
    }
}
