/*
 * This source file was generated by the Gradle 'init' task
 */
package kr.jinsu.jdbc_ex;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Scanner;

import kr.jinsu.helpers.DBHelper;

public class Ex03_InsertEx {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);

        System.out.print("학과 이름을 입력하세요: ");
        String dname = scanner.nextLine();

        System.out.print("학과의 위치를 입력하세요: ");
        String loc = scanner.nextLine();

        scanner.close();

        Connection conn = DBHelper.getInstance().open();

        String sql = "INSERT INTO department (dname, loc) VALUES ('" + dname + "', '" + loc + "')";
        Statement stmt = null;
        // 결과값 (저장된 데이터의 수)
        int result = 0;

        try {
            stmt = conn.createStatement();
            result = stmt.executeUpdate(sql);
        } catch (SQLException e) {
            System.out.println("===== Query Error =====");
            e.printStackTrace();
        } finally {
            if(stmt != null) {
                try {
                    stmt.close();
                } catch (SQLException e) {
                    e.printStackTrace();
                }  
            }
        }

        //결과 출력
        System.out.println(result + "개의 데이터가 저장됨");

        /** 데이터베이스의 접속을 해제한다. */
        DBHelper.getInstance().close();
    }
}
