/*
 * This source file was generated by the Gradle 'init' task
 */
package kr.jinsu.jdbc_ex;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

import kr.jinsu.helpers.DBHelper;

public class Ex04_UpdateEx {
    public static void main(String[] args) {
        Connection conn = DBHelper.getInstance().open();

        String sql = "UPDATE department SET dname='hello', loc='world' WHERE deptno >= 103";

        Statement stmt = null;
        int result = 0;

        try {
            stmt = conn.createStatement();
            result = stmt.executeUpdate(sql);
        } catch (SQLException e) {
            System.out.println("===== Query Error =====");
            e.printStackTrace();
        } finally {
            if(stmt != null) {
                try {
                    stmt.close();
                } catch (SQLException e) {
                    e.printStackTrace();
                }  
            }
        }

        //결과 출력
        System.out.println(result + "개의 데이터가 수정됨");

        /** 데이터베이스의 접속을 해제한다. */
        DBHelper.getInstance().close();
    }
}
