/*
 * This source file was generated by the Gradle 'init' task
 */
package kr.jinsu.jdbc_ex;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import kr.jinsu.helpers.DBHelper;

public class Ex06_SelectEx {
    public static void main(String[] args) {
        Connection conn = DBHelper.getInstance().open();

        String sql = "SELECT deptno, dname, loc FROM department ORDER BY deptno ASC";

        // SQL문을 실행할 수 있는 객체
        Statement stmt = null;
        // 결과값 (저장된 데이터의 수)
        ResultSet rs = null;

        try {
            stmt = conn.createStatement();
            rs = stmt.executeQuery(sql);

            while (rs.next()) {
                int deptNo = rs.getInt("deptno");
                String dname = rs.getString("dname");
                String loc = rs.getString("loc");

                System.out.printf("학과번호: %d\n", deptNo);
                System.out.printf("학과이름: %s\n", dname);
                System.out.printf("위치: %s\n", loc);
                System.out.println();
            }
        } catch (SQLException e) {
            System.out.println("===== Query Error =====");
            e.printStackTrace();
        } finally {
            // SQL 구문의 에러 여부에 상관없이 stmt 객체를 닫기 위하여 finally 블록 사용.
            // --> 객체의 유효범위 설ㅈ정을 위해서 stmt 객체는 try 블록 밖에 선언되었다.
            if(stmt != null) {
                try {
                    stmt.close();
                } catch (SQLException e) {
                    e.printStackTrace();
                }  
            }
        }
        DBHelper.getInstance().close();
    }
}
