/*
 * This source file was generated by the Gradle 'init' task
 */
package kr.jinsu.jdbc_ex;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import kr.jinsu.helpers.DBHelper;

public class Ex07_CountEx {
    public static void main(String[] args) {
        Connection conn = DBHelper.getInstance().open();

        // 4학년 학생의 수
        String sql = "SELECT COUNT(*) cnt FROM student WHERE grade=4";

        // SQL문을 실행할 수 있는 객체
        Statement stmt = null;

        // 결과값 (저장된 데이터의 수)
        ResultSet rs = null;

        try {
            stmt = conn.createStatement();
            rs = stmt.executeQuery(sql);

            //조회 결과의 첫 번째 줄로 이동
            boolean first = rs.next();
            
            if(first) {
                //select절에 명시된 `1`번째 항목을 int 형으로 추출하기
                //int count = rs.getInt(1);

                //select절에 명시된 `cnt`컬럼을 int형으로 추출하기
                int count = rs.getInt("cnt");

                System.out.println("4학년 학생은 " + count + "명 입니다.");
            }
        } catch (SQLException e) {
            System.out.println("===== Query Error =====");
            e.printStackTrace();
        } finally {
            // SQL 구문의 에러 여부에 상관없이 stmt 객체를 닫기 위하여 finally 블록 사용.
            // --> 객체의 유효범위 설ㅈ정을 위해서 stmt 객체는 try 블록 밖에 선언되었다.
            if(stmt != null) {
                try {
                    stmt.close();
                } catch (SQLException e) {
                    e.printStackTrace();
                }  
            }
        }
        DBHelper.getInstance().close();
    }
}
