/*
 * This source file was generated by the Gradle 'init' task
 */
package kr.jinsu.jdbc_ex;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Scanner;

import kr.jinsu.helpers.DBHelper;

public class Ex08_SearchEx {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);

        System.out.print("아이디를 입력하세요: ");
        String userId = scanner.nextLine();

        System.out.print("비밀번호를 입력하세요: ");
        String idnum = scanner.nextLine();

        scanner.close();

        Connection conn = DBHelper.getInstance().open();

        // '김도훈' 교수의 정보 조회하기
        String sql = "SELECT studno, s.name, grade, birthdate, tel, height, weight, dname, p.name "
        + "FROM student s "
        + "INNER JOIN department d ON s.deptno = d.deptno "
        + "INNER JOIN professor p ON s.profno = p.profno "
        + "WHERE s.userid='" + userId + "' AND idnum='" + idnum + "'";

        // SQL문을 실행할 수 있는 객체
        Statement stmt = null;

        // 결과값 (저장된 데이터의 수)
        ResultSet rs = null;

        try {
            stmt = conn.createStatement();
            rs = stmt.executeQuery(sql);
            
            while(rs.next()) {
                // select절에 명시한 컬럼 이름을 사용하여 데이터 추출
                int studNo = rs.getInt("studno");
                String name = rs.getString("s.name");
                int grade = rs.getInt("grade");
                String birthdate = rs.getString("birthdate");
                String tel = rs.getString("tel");
                int height = rs.getInt("height");
                int weight = rs.getInt("weight");
                String dname = rs.getString("dname");
                String profName = rs.getString("p.name");

                //결과출력
                System.out.println("학번: " + studNo);
                System.out.println("이름: " + name);
                System.out.println("학년: " + grade);
                System.out.println("생년월일: " + birthdate);
                System.out.println("전화번호: " + tel);
                System.out.println("키: " + height);
                System.out.println("몸무게: " + weight);
                System.out.println("학과: " + dname);
                System.out.println("지도교수: " + profName);
                System.out.println();

            }
        } catch (SQLException e) {
            System.out.println("===== Query Error =====");
            e.printStackTrace();
        } finally {
            // SQL 구문의 에러 여부에 상관없이 stmt 객체를 닫기 위하여 finally 블록 사용.
            // --> 객체의 유효범위 설정을 위해서 stmt 객체는 try 블록 밖에 선언되었다.
            if(stmt != null) {
                try {
                    stmt.close();
                } catch (SQLException e) {
                    e.printStackTrace();
                }  
            }
        }
        DBHelper.getInstance().close();
    }
}
